#from https://about.gitlab.com/blog/build-a-new-website-in-a-few-easy-steps-with-gitlab-pages/
pages:
  image: node:18-alpine # Example: Using a Node.js image for a JavaScript-based static site generator
  stage: deploy
  script:
    - echo "Deploying application ..."
    - echo "Make temp dir '.public' ..."
    - mkdir .public
    - echo "Copies all website files into temp dir ('.public') ..."
    - cp -r * .public
    - echo "Renames temp dir ('.public') into 'public' ..."
    - mv .public public
    - echo "Application successfully deployed."
  artifacts:
    paths:
      - public
  only:
    - main