#from https://about.gitlab.com/blog/build-a-new-website-in-a-few-easy-steps-with-gitlab-pages/
# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script: []
pages:
  script:
    - echo "Deploying application ..."
    - echo "Make temp dir '.public' ..."
    - mkdir .public
    - echo "Copies all website files into temp dir ('.public') ..."
    - cp -r * .public
    - echo "Renames temp dir ('.public') into 'public' ..."
    - mv .public public
    - echo "Application successfully deployed."
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
    only:
    - main
